from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_autosoft(object):
    def setupUi(self, autosoft):
        autosoft.setObjectName("autosoft")
        autosoft.resize(530, 432)
        autosoft.setMouseTracking(True)
        autosoft.setTabletTracking(True)
        self.log_in = QtWidgets.QPushButton(autosoft)
        self.log_in.setEnabled(False)
        self.log_in.setGeometry(QtCore.QRect(240, 330, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.log_in.setFont(font)
        self.log_in.setObjectName("log_in")
        self.password = QtWidgets.QLineEdit(autosoft)
        self.password.setGeometry(QtCore.QRect(170, 290, 201, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.password.setFont(font)
        self.password.setTabletTracking(True)
        self.password.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.password.setAutoFillBackground(False)
        self.password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setDragEnabled(True)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.user = QtWidgets.QLineEdit(autosoft)
        self.user.setGeometry(QtCore.QRect(170, 220, 201, 21))
        self.user.setMouseTracking(True)
        self.user.setObjectName("user")
        self.user_2 = QtWidgets.QLabel(autosoft)
        self.user_2.setGeometry(QtCore.QRect(170, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.user_2.setFont(font)
        self.user_2.setObjectName("user_2")
        self.password_2 = QtWidgets.QLabel(autosoft)
        self.password_2.setGeometry(QtCore.QRect(170, 260, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.password_2.setFont(font)
        self.password_2.setObjectName("password_2")
        self.line = QtWidgets.QFrame(autosoft)
        self.line.setGeometry(QtCore.QRect(170, 360, 201, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.image = QtWidgets.QLabel(autosoft)
        self.image.setGeometry(QtCore.QRect(-20, 0, 561, 171))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("../4.png"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")

        self.retranslateUi(autosoft)
        self.user.editingFinished.connect(self.password.setFocus) # type: ignore
        self.password.selectionChanged.connect(self.log_in.toggle) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(autosoft)
        autosoft.setTabOrder(self.user, self.password)
        autosoft.setTabOrder(self.password, self.log_in)
        self.user.textChanged.connect(self.on_text_changed)
        self.password.textChanged.connect(self.on_text_changed)
        
    def retranslateUi(self, autosoft):
        _translate = QtCore.QCoreApplication.translate
        autosoft.setWindowTitle(_translate("autosoft", "Autosoft 2.1"))
        self.log_in.setText(_translate("autosoft", "Log In"))
        self.user_2.setText(_translate("autosoft", "Usuario:"))
        self.password_2.setText(_translate("autosoft", "Password:"))

    def on_text_changed(self): # Activa el boton de login si se inserto texto en user y password
        self.log_in.setEnabled(bool(self.user.text()) and bool(self.password.text()))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autosoft = QtWidgets.QDialog()
    ui = Ui_autosoft()
    ui.setupUi(autosoft)
    autosoft.show()
    sys.exit(app.exec_())
